var bodyBgs = [];
bodyBgs[0] = "http://qfrqgh8aw.hn-bkt.clouddn.com/1.mp3";
bodyBgs[1] = "http://qfrqgh8aw.hn-bkt.clouddn.com/2.mp3";
bodyBgs[2] = "http://qfrqgh8aw.hn-bkt.clouddn.com/3.mp3";
bodyBgs[3] = "http://qfrqgh8aw.hn-bkt.clouddn.com/4.mp3";
bodyBgs[4] = "http://qfrqgh8aw.hn-bkt.clouddn.com/5.mp3";
bodyBgs[5] = "http://qfrqgh8aw.hn-bkt.clouddn.com/6.mp3";
bodyBgs[6] = "http://qfrqgh8aw.hn-bkt.clouddn.com/7.mp3";
bodyBgs[7] = "http://qfrqgh8aw.hn-bkt.clouddn.com/8.mp3";
bodyBgs[8] = "http://qfrqgh8aw.hn-bkt.clouddn.com/9.mp3";
bodyBgs[9] = "http://qfrqgh8aw.hn-bkt.clouddn.com/10.mp3";
bodyBgs[10] = "http://qfrqgh8aw.hn-bkt.clouddn.com/11.mp3";
bodyBgs[11] = "http://qfrqgh8aw.hn-bkt.clouddn.com/12.mp3";
bodyBgs[12] = "http://qfrqgh8aw.hn-bkt.clouddn.com/13.mp3";
bodyBgs[13] = "http://qfrqgh8aw.hn-bkt.clouddn.com/14.mp3";
bodyBgs[14] = "http://qfrqgh8aw.hn-bkt.clouddn.com/15.mp3";
bodyBgs[15] = "http://qfrqgh8aw.hn-bkt.clouddn.com/16.mp3";
bodyBgs[16] = "http://qfrqgh8aw.hn-bkt.clouddn.com/17.mp3";
bodyBgs[17] = "http://qfrqgh8aw.hn-bkt.clouddn.com/18.mp3";
bodyBgs[18] = "http://qfrqgh8aw.hn-bkt.clouddn.com/19.mp3";
bodyBgs[19] = "http://qfrqgh8aw.hn-bkt.clouddn.com/20.mp3";
bodyBgs[20] = "http://qfrqgh8aw.hn-bkt.clouddn.com/21.mp3";
bodyBgs[21] = "http://qfrqgh8aw.hn-bkt.clouddn.com/22.mp3";
bodyBgs[22] = "http://qfrqgh8aw.hn-bkt.clouddn.com/23.mp3";
bodyBgs[23] = "http://qfrqgh8aw.hn-bkt.clouddn.com/24.mp3";
bodyBgs[24] = "http://qfrqgh8aw.hn-bkt.clouddn.com/25.mp3";
bodyBgs[25] = "http://qfrqgh8aw.hn-bkt.clouddn.com/26.mp3";
bodyBgs[26] = "http://qfrqgh8aw.hn-bkt.clouddn.com/27.mp3";
bodyBgs[27] = "http://qfrqgh8aw.hn-bkt.clouddn.com/28.mp3";
bodyBgs[28] = "http://qfrqgh8aw.hn-bkt.clouddn.com/29.mp3";
bodyBgs[29] = "http://qfrqgh8aw.hn-bkt.clouddn.com/30.mp3";
bodyBgs[30] = "http://qfrqgh8aw.hn-bkt.clouddn.com/31.mp3";
bodyBgs[31] = "http://qfrqgh8aw.hn-bkt.clouddn.com/32.mp3";
bodyBgs[32] = "http://qfrqgh8aw.hn-bkt.clouddn.com/33.mp3";
bodyBgs[33] = "http://qfrqgh8aw.hn-bkt.clouddn.com/34.mp3";
bodyBgs[34] = "http://qfrqgh8aw.hn-bkt.clouddn.com/35.mp3";
bodyBgs[35] = "http://qfrqgh8aw.hn-bkt.clouddn.com/36.mp3";
bodyBgs[36] = "http://qfrqgh8aw.hn-bkt.clouddn.com/37.mp3";
bodyBgs[37] = "http://qfrqgh8aw.hn-bkt.clouddn.com/38.mp3";
bodyBgs[38] = "http://qfrqgh8aw.hn-bkt.clouddn.com/39.mp3";
bodyBgs[39] = "http://qfrqgh8aw.hn-bkt.clouddn.com/40.mp3";
bodyBgs[40] = "http://qfrqgh8aw.hn-bkt.clouddn.com/41.mp3";
bodyBgs[41] = "http://qfrqgh8aw.hn-bkt.clouddn.com/42.mp3";
bodyBgs[42] = "http://qfrqgh8aw.hn-bkt.clouddn.com/43.mp3";
bodyBgs[43] = "http://qfrqgh8aw.hn-bkt.clouddn.com/44.mp3";
bodyBgs[44] = "http://qfrqgh8aw.hn-bkt.clouddn.com/45.mp3";
bodyBgs[45] = "http://qfrqgh8aw.hn-bkt.clouddn.com/46.mp3";
bodyBgs[46] = "http://qfrqgh8aw.hn-bkt.clouddn.com/47.mp3";
bodyBgs[47] = "http://qfrqgh8aw.hn-bkt.clouddn.com/48.mp3";
bodyBgs[48] = "http://qfrqgh8aw.hn-bkt.clouddn.com/49.mp3";
bodyBgs[49] = "http://qfrqgh8aw.hn-bkt.clouddn.com/50.mp3";
bodyBgs[50] = "http://qfrqgh8aw.hn-bkt.clouddn.com/51.mp3";
bodyBgs[51] = "http://qfrqgh8aw.hn-bkt.clouddn.com/52.mp3";
bodyBgs[52] = "http://qfrqgh8aw.hn-bkt.clouddn.com/53.mp3";
bodyBgs[53] = "http://qfrqgh8aw.hn-bkt.clouddn.com/54.mp3";
bodyBgs[55] = "http://qfrqgh8aw.hn-bkt.clouddn.com/55.mp3";
bodyBgs[55] = "http://qfrqgh8aw.hn-bkt.clouddn.com/56.mp3";
bodyBgs[56] = "http://qfrqgh8aw.hn-bkt.clouddn.com/57.mp3";
bodyBgs[57] = "http://qfrqgh8aw.hn-bkt.clouddn.com/58.mp3";
bodyBgs[58] = "http://qfrqgh8aw.hn-bkt.clouddn.com/59.mp3";
bodyBgs[59] = "http://qfrqgh8aw.hn-bkt.clouddn.com/50.mp3";
bodyBgs[60] = "http://qfrqgh8aw.hn-bkt.clouddn.com/61.mp3";
bodyBgs[61] = "http://qfrqgh8aw.hn-bkt.clouddn.com/62.mp3";
bodyBgs[62] = "http://qfrqgh8aw.hn-bkt.clouddn.com/63.mp3";
bodyBgs[63] = "http://qfrqgh8aw.hn-bkt.clouddn.com/64.mp3";
bodyBgs[64] = "http://qfrqgh8aw.hn-bkt.clouddn.com/65.mp3";
bodyBgs[65] = "http://qfrqgh8aw.hn-bkt.clouddn.com/66.mp3";
bodyBgs[66] = "http://qfrqgh8aw.hn-bkt.clouddn.com/67.mp3";
bodyBgs[67] = "http://qfrqgh8aw.hn-bkt.clouddn.com/68.mp3";
bodyBgs[68] = "http://qfrqgh8aw.hn-bkt.clouddn.com/69.mp3";
bodyBgs[69] = "http://qfrqgh8aw.hn-bkt.clouddn.com/70.mp3";
bodyBgs[70] = "http://qfrqgh8aw.hn-bkt.clouddn.com/71.mp3";
bodyBgs[71] = "http://qfrqgh8aw.hn-bkt.clouddn.com/72.mp3";
bodyBgs[72] = "http://qfrqgh8aw.hn-bkt.clouddn.com/73.mp3";
bodyBgs[73] = "http://qfrqgh8aw.hn-bkt.clouddn.com/74.mp3";
bodyBgs[74] = "http://qfrqgh8aw.hn-bkt.clouddn.com/75.mp3";
bodyBgs[75] = "http://qfrqgh8aw.hn-bkt.clouddn.com/76.mp3";
bodyBgs[76] = "http://qfrqgh8aw.hn-bkt.clouddn.com/77.mp3";
bodyBgs[77] = "http://qfrqgh8aw.hn-bkt.clouddn.com/78.mp3";
bodyBgs[78] = "http://qfrqgh8aw.hn-bkt.clouddn.com/79.mp3";
bodyBgs[79] = "http://qfrqgh8aw.hn-bkt.clouddn.com/80.mp3";
bodyBgs[80] = "http://qfrqgh8aw.hn-bkt.clouddn.com/81.mp3";
bodyBgs[81] = "http://qfrqgh8aw.hn-bkt.clouddn.com/82.mp3";
bodyBgs[82] = "http://qfrqgh8aw.hn-bkt.clouddn.com/83.mp3";
bodyBgs[83] = "http://qfrqgh8aw.hn-bkt.clouddn.com/84.mp3";
bodyBgs[84] = "http://qfrqgh8aw.hn-bkt.clouddn.com/85.mp3";
bodyBgs[85] = "http://qfrqgh8aw.hn-bkt.clouddn.com/86.mp3";
bodyBgs[86] = "http://qfrqgh8aw.hn-bkt.clouddn.com/87.mp3";
bodyBgs[87] = "http://qfrqgh8aw.hn-bkt.clouddn.com/88.mp3";
bodyBgs[88] = "http://qfrqgh8aw.hn-bkt.clouddn.com/89.mp3";
bodyBgs[89] = "http://qfrqgh8aw.hn-bkt.clouddn.com/90.mp3";
bodyBgs[90] = "http://qfrqgh8aw.hn-bkt.clouddn.com/91.mp3";
bodyBgs[91] = "http://qfrqgh8aw.hn-bkt.clouddn.com/92.mp3";
bodyBgs[92] = "http://qfrqgh8aw.hn-bkt.clouddn.com/93.mp3";
bodyBgs[93] = "http://qfrqgh8aw.hn-bkt.clouddn.com/94.mp3";
bodyBgs[94] = "http://qfrqgh8aw.hn-bkt.clouddn.com/95.mp3";
bodyBgs[95] = "http://qfrqgh8aw.hn-bkt.clouddn.com/96.mp3";
bodyBgs[96] = "http://qfrqgh8aw.hn-bkt.clouddn.com/97.mp3";
bodyBgs[97] = "http://qfrqgh8aw.hn-bkt.clouddn.com/98.mp3";
bodyBgs[98] = "http://qfrqgh8aw.hn-bkt.clouddn.com/99.mp3";
bodyBgs[99] = "http://qfrqgh8aw.hn-bkt.clouddn.com/100.mp3";
bodyBgs[100] = "http://qfrqgh8aw.hn-bkt.clouddn.com/101.mp3";
bodyBgs[101] = "http://qfrqgh8aw.hn-bkt.clouddn.com/102.mp3";
bodyBgs[102] = "http://qfrqgh8aw.hn-bkt.clouddn.com/103.mp3";
bodyBgs[103] = "http://qfrqgh8aw.hn-bkt.clouddn.com/104.mp3";
bodyBgs[104] = "http://qfrqgh8aw.hn-bkt.clouddn.com/105.mp3";
bodyBgs[105] = "http://qfrqgh8aw.hn-bkt.clouddn.com/106.mp3";
bodyBgs[106] = "http://qfrqgh8aw.hn-bkt.clouddn.com/107.mp3";
bodyBgs[107] = "http://qfrqgh8aw.hn-bkt.clouddn.com/108.mp3";
bodyBgs[108] = "http://qfrqgh8aw.hn-bkt.clouddn.com/109.mp3";
bodyBgs[109] = "http://qfrqgh8aw.hn-bkt.clouddn.com/110.mp3";
bodyBgs[110] = "http://qfrqgh8aw.hn-bkt.clouddn.com/111.mp3";
bodyBgs[111] = "http://qfrqgh8aw.hn-bkt.clouddn.com/112.mp3";
bodyBgs[112] = "http://qfrqgh8aw.hn-bkt.clouddn.com/113.mp3";
bodyBgs[113] = "http://qfrqgh8aw.hn-bkt.clouddn.com/114.mp3";
bodyBgs[114] = "http://qfrqgh8aw.hn-bkt.clouddn.com/115.mp3";
bodyBgs[115] = "http://qfrqgh8aw.hn-bkt.clouddn.com/116.mp3";
bodyBgs[116] = "http://qfrqgh8aw.hn-bkt.clouddn.com/117.mp3";
bodyBgs[117] = "http://qfrqgh8aw.hn-bkt.clouddn.com/118.mp3";
bodyBgs[118] = "http://qfrqgh8aw.hn-bkt.clouddn.com/119.mp3";
bodyBgs[119] = "http://qfrqgh8aw.hn-bkt.clouddn.com/120.mp3";
bodyBgs[120] = "http://qfrqgh8aw.hn-bkt.clouddn.com/121.mp3";
bodyBgs[121] = "http://qfrqgh8aw.hn-bkt.clouddn.com/122.mp3";
bodyBgs[122] = "http://qfrqgh8aw.hn-bkt.clouddn.com/123.mp3";
bodyBgs[123] = "http://qfrqgh8aw.hn-bkt.clouddn.com/124.mp3";
var randomBgIndex = Math.round(Math.random() * 123);
document.write('<audio id=\'Jaudio\' src=\'' + bodyBgs[randomBgIndex] + '\'autoplay=\'autoplay\'></audio>');
//]]>；
function audioAutoPlay(id) {
	var audio = document.getElementById(id),
	play = function() {
		audio.play();
		document.removeEventListener("touchstart", play, false);
	};
	audio.play();
	document.addEventListener("WeixinJSBridgeReady",
	function() {
		play();
	},
	false);
	document.addEventListener("touchstart", play, false);
}
audioAutoPlay('Jaudio');
var audio = document.getElementById("Jaudio");
audio.loop = false;
audio.addEventListener('ended',
function() {
	location.reload();
},
false);