var bodyBgs = [];
bodyBgs[0] = "https://snakekisscdn.imfast.io/1.mp3";
bodyBgs[1] = "https://snakekisscdn.imfast.io/2.mp3";
bodyBgs[2] = "https://snakekisscdn.imfast.io/3.mp3";
bodyBgs[3] = "https://snakekisscdn.imfast.io/4.mp3";
bodyBgs[4] = "https://snakekisscdn.imfast.io/5.mp3";
bodyBgs[5] = "https://snakekisscdn.imfast.io/6.mp3";
bodyBgs[6] = "https://snakekisscdn.imfast.io/7.mp3";
bodyBgs[7] = "https://snakekisscdn.imfast.io/8.mp3";
bodyBgs[8] = "https://snakekisscdn.imfast.io/9.mp3";
bodyBgs[9] = "https://snakekisscdn.imfast.io/10.mp3";
bodyBgs[10] = "https://snakekisscdn.imfast.io/11.mp3";
bodyBgs[11] = "https://snakekisscdn.imfast.io/12.mp3";
bodyBgs[12] = "https://snakekisscdn.imfast.io/13.mp3";
bodyBgs[13] = "https://snakekisscdn.imfast.io/14.mp3";
bodyBgs[14] = "https://snakekisscdn.imfast.io/15.mp3";
bodyBgs[15] = "https://snakekisscdn.imfast.io/16.mp3";
bodyBgs[16] = "https://snakekisscdn.imfast.io/17.mp3";
bodyBgs[17] = "https://snakekisscdn.imfast.io/18.mp3";
bodyBgs[18] = "https://snakekisscdn.imfast.io/19.mp3";
bodyBgs[19] = "https://snakekisscdn.imfast.io/20.mp3";
bodyBgs[20] = "https://snakekisscdn.imfast.io/21.mp3";
bodyBgs[21] = "https://snakekisscdn.imfast.io/22.mp3";
bodyBgs[22] = "https://snakekisscdn.imfast.io/23.mp3";
bodyBgs[23] = "https://snakekisscdn.imfast.io/24.mp3";
bodyBgs[24] = "https://snakekisscdn.imfast.io/25.mp3";
bodyBgs[25] = "https://snakekisscdn.imfast.io/26.mp3";
bodyBgs[26] = "https://snakekisscdn.imfast.io/27.mp3";
bodyBgs[27] = "https://snakekisscdn.imfast.io/28.mp3";
bodyBgs[28] = "https://snakekisscdn.imfast.io/29.mp3";
bodyBgs[29] = "https://snakekisscdn.imfast.io/30.mp3";
bodyBgs[30] = "https://snakekisscdn.imfast.io/31.mp3";
bodyBgs[31] = "https://snakekisscdn.imfast.io/32.mp3";
bodyBgs[32] = "https://snakekisscdn.imfast.io/33.mp3";
bodyBgs[33] = "https://snakekisscdn.imfast.io/34.mp3";
bodyBgs[34] = "https://snakekisscdn.imfast.io/35.mp3";
bodyBgs[35] = "https://snakekisscdn.imfast.io/36.mp3";
bodyBgs[36] = "https://snakekisscdn.imfast.io/37.mp3";
bodyBgs[37] = "https://snakekisscdn.imfast.io/38.mp3";
bodyBgs[38] = "https://snakekisscdn.imfast.io/39.mp3";
bodyBgs[39] = "https://snakekisscdn.imfast.io/40.mp3";
bodyBgs[40] = "https://snakekisscdn.imfast.io/41.mp3";
bodyBgs[41] = "https://snakekisscdn.imfast.io/42.mp3";
bodyBgs[42] = "https://snakekisscdn.imfast.io/43.mp3";
bodyBgs[43] = "https://snakekisscdn.imfast.io/44.mp3";
bodyBgs[44] = "https://snakekisscdn.imfast.io/45.mp3";
bodyBgs[45] = "https://snakekisscdn.imfast.io/46.mp3";
bodyBgs[46] = "https://snakekisscdn.imfast.io/47.mp3";
bodyBgs[47] = "https://snakekisscdn.imfast.io/48.mp3";
bodyBgs[48] = "https://snakekisscdn.imfast.io/49.mp3";
bodyBgs[49] = "https://snakekisscdn.imfast.io/50.mp3";
bodyBgs[50] = "https://snakekisscdn.imfast.io/51.mp3";
bodyBgs[51] = "https://snakekisscdn.imfast.io/52.mp3";
bodyBgs[52] = "https://snakekisscdn.imfast.io/53.mp3";
bodyBgs[53] = "https://snakekisscdn.imfast.io/54.mp3";
bodyBgs[55] = "https://snakekisscdn.imfast.io/55.mp3";
bodyBgs[55] = "https://snakekisscdn.imfast.io/56.mp3";
bodyBgs[56] = "https://snakekisscdn.imfast.io/57.mp3";
bodyBgs[57] = "https://snakekisscdn.imfast.io/58.mp3";
bodyBgs[58] = "https://snakekisscdn.imfast.io/59.mp3";
bodyBgs[59] = "https://snakekisscdn.imfast.io/50.mp3";
bodyBgs[60] = "https://snakekisscdn.imfast.io/61.mp3";
bodyBgs[61] = "https://snakekisscdn.imfast.io/62.mp3";
bodyBgs[62] = "https://snakekisscdn.imfast.io/63.mp3";
bodyBgs[63] = "https://snakekisscdn.imfast.io/64.mp3";
bodyBgs[64] = "https://snakekisscdn.imfast.io/65.mp3";
bodyBgs[65] = "https://snakekisscdn.imfast.io/66.mp3";
bodyBgs[66] = "https://snakekisscdn.imfast.io/67.mp3";
bodyBgs[67] = "https://snakekisscdn.imfast.io/68.mp3";
bodyBgs[68] = "https://snakekisscdn.imfast.io/69.mp3";
bodyBgs[69] = "https://snakekisscdn.imfast.io/70.mp3";
bodyBgs[70] = "https://snakekisscdn.imfast.io/71.mp3";
bodyBgs[71] = "https://snakekisscdn.imfast.io/72.mp3";
bodyBgs[72] = "https://snakekisscdn.imfast.io/73.mp3";
bodyBgs[73] = "https://snakekisscdn.imfast.io/74.mp3";
bodyBgs[74] = "https://snakekisscdn.imfast.io/75.mp3";
bodyBgs[75] = "https://snakekisscdn.imfast.io/76.mp3";
bodyBgs[76] = "https://snakekisscdn.imfast.io/77.mp3";
bodyBgs[77] = "https://snakekisscdn.imfast.io/78.mp3";
bodyBgs[78] = "https://snakekisscdn.imfast.io/79.mp3";
bodyBgs[79] = "https://snakekisscdn.imfast.io/80.mp3";
bodyBgs[80] = "https://snakekisscdn.imfast.io/81.mp3";
bodyBgs[81] = "https://snakekisscdn.imfast.io/82.mp3";
bodyBgs[82] = "https://snakekisscdn.imfast.io/83.mp3";
bodyBgs[83] = "https://snakekisscdn.imfast.io/84.mp3";
bodyBgs[84] = "https://snakekisscdn.imfast.io/85.mp3";
bodyBgs[85] = "https://snakekisscdn.imfast.io/86.mp3";
bodyBgs[86] = "https://snakekisscdn.imfast.io/87.mp3";
bodyBgs[87] = "https://snakekisscdn.imfast.io/88.mp3";
bodyBgs[88] = "https://snakekisscdn.imfast.io/89.mp3";
bodyBgs[89] = "https://snakekisscdn.imfast.io/90.mp3";
bodyBgs[90] = "https://snakekisscdn.imfast.io/91.mp3";
bodyBgs[91] = "https://snakekisscdn.imfast.io/92.mp3";
bodyBgs[92] = "https://snakekisscdn.imfast.io/93.mp3";
bodyBgs[93] = "https://snakekisscdn.imfast.io/94.mp3";
bodyBgs[94] = "https://snakekisscdn.imfast.io/95.mp3";
bodyBgs[95] = "https://snakekisscdn.imfast.io/96.mp3";
bodyBgs[96] = "https://snakekisscdn.imfast.io/97.mp3";
bodyBgs[97] = "https://snakekisscdn.imfast.io/98.mp3";
bodyBgs[98] = "https://snakekisscdn.imfast.io/99.mp3";
bodyBgs[99] = "https://snakekisscdn.imfast.io/100.mp3";
bodyBgs[100] = "https://snakekisscdn.imfast.io/101.mp3";
bodyBgs[101] = "https://snakekisscdn.imfast.io/102.mp3";
bodyBgs[102] = "https://snakekisscdn.imfast.io/103.mp3";
bodyBgs[103] = "https://snakekisscdn.imfast.io/104.mp3";
bodyBgs[104] = "https://snakekisscdn.imfast.io/105.mp3";
bodyBgs[105] = "https://snakekisscdn.imfast.io/106.mp3";
bodyBgs[106] = "https://snakekisscdn.imfast.io/107.mp3";
bodyBgs[107] = "https://snakekisscdn.imfast.io/108.mp3";
bodyBgs[108] = "https://snakekisscdn.imfast.io/109.mp3";
bodyBgs[109] = "https://snakekisscdn.imfast.io/110.mp3";
bodyBgs[110] = "https://snakekisscdn.imfast.io/111.mp3";
bodyBgs[111] = "https://snakekisscdn.imfast.io/112.mp3";
bodyBgs[112] = "https://snakekisscdn.imfast.io/113.mp3";
bodyBgs[113] = "https://snakekisscdn.imfast.io/114.mp3";
bodyBgs[114] = "https://snakekisscdn.imfast.io/115.mp3";
bodyBgs[115] = "https://snakekisscdn.imfast.io/116.mp3";
bodyBgs[116] = "https://snakekisscdn.imfast.io/117.mp3";
bodyBgs[117] = "https://snakekisscdn.imfast.io/118.mp3";
bodyBgs[118] = "https://snakekisscdn.imfast.io/119.mp3";
bodyBgs[119] = "https://snakekisscdn.imfast.io/120.mp3";
bodyBgs[120] = "https://snakekisscdn.imfast.io/121.mp3";
bodyBgs[121] = "https://snakekisscdn.imfast.io/122.mp3";
bodyBgs[122] = "https://snakekisscdn.imfast.io/123.mp3";
bodyBgs[123] = "https://snakekisscdn.imfast.io/124.mp3";
var randomBgIndex = Math.round(Math.random() * 123);
document.write('<audio id=\'Jaudio\' src=\'' + bodyBgs[randomBgIndex] + '\'autoplay=\'autoplay\'></audio>');
//]]>；
function audioAutoPlay(id) {
	var audio = document.getElementById(id),
	play = function() {
		audio.play();
		document.removeEventListener("touchstart", play, false);
	};
	audio.play();
	document.addEventListener("WeixinJSBridgeReady",
	function() {
		play();
	},
	false);
	document.addEventListener("touchstart", play, false);
}
audioAutoPlay('Jaudio');
var audio = document.getElementById("Jaudio");
audio.loop = false;
audio.addEventListener('ended',
function() {
	location.reload();
},
false);